### ISSUE TITLE
Links in examples are broken

### ISSUE THREAD

**Issue by charlottemach** [antonbabenko/terraform-best-practices#18]
## Describe the bug
Some of the links in the terraform-best-practices/examples folder are broken (e.g. https://github.com/antonbabenko/terraform-best-practices/blob/master/examples/terraform/terraform.md#terraform-small).

## Expected change
The links should lead to the correct folders, e.g. https://github.com/antonbabenko/terraform-best-practices/tree/master/examples/small-terraform .

**Comment by antonbabenko** [comment]
The links are correct in the book.

---

I've just updated the book and code very much (recent version of Terraform, spelling mistakes, oops) - https://www.terraform-best-practices.com/

If there are any questions, please raise them here.

I or someone else will try to reply faster than in 2 years (sorry for that!)
