### ISSUE TITLE
Please consider changing the name recommendation of "this"

### ISSUE THREAD

**Issue by farnsworth2008** [antonbabenko/terraform-best-practices#24]
The [terraform naming conventions ](https://www.terraform-best-practices.com/naming) currently recommends "this" as a default resource name.  While I agree with the majority of what you have written I think using "main" as a default name would be a better recommendation.

in many software languages where "this" is a formal feature it is used as a token only for private references from within the component to its self.  Using "this" for other components to refer to each other seems strange.  The term "main" is more general and would work in this context.

How do you feel about making the change?  If you agree, I can draft a pull request to update the documentation.

**Comment by antonbabenko** [comment]
"this", "main", or "self" - is not so important how to call it as long as the _name_ does not mean anything concrete.

Renaming things at this stage is not feasible because it brings no visible value to anyone.

Closing this issue.
