### ISSUE TITLE
Adding Japanese Translation Pages

### ISSUE THREAD

**Issue by shogo452** [antonbabenko/terraform-best-practices#62]
## Is your feature request related to a problem? Please describe.
`日本語(Japanese)` appears in the language selection dropdown menu, but there are no Japanese pages.

## Describe the solution you'd like
May I contribute my Japanese translations of the pages?

**Comment by antonbabenko** [comment]
Thanks for asking. Takashi has been working on it since yesterday. I will ask him if he needs help.

**Comment by shogo452** [comment]
@antonbabenko 
Thank you for your response and asking to Takashi-san.
Please let me know if there's anything I can do to help.

**Comment by antonbabenko** [comment]
I or Takashi-san will let you know if there is a need. Thanks again for reaching out!

**Comment by t-okamoto1122** [comment]
@shogo452 
Of course, I'd be happy to have your help! ありがとうございます！！

I thought it might be good to roughly decide on who will handle just the first few pages. After that, I think it would be good to decide responsibilities based on each other’s pace.
These are the list of pages. If you have a page you would like to be in charge of, please let me know.

- Welcome ( `Takashi`
- Key concepts ( `Takashi`
- Code structure
- Code structure examples
- Naming conventions
- Code styling
- FAQ
- References
- Writing Terraform configurations
- Workshop

**Comment by shogo452** [comment]
@t-okamoto1122 
Thank you for your comment. And thank you also for sharing the page list. よろしくお願いします！
I would like to be in charge of `Code structure` and `Naming conventions`.

* Welcome ( `Takashi`
* Key concepts ( `Takashi`
* Code structure ( `Shogo`
* Code structure examples
* Naming conventions ( `Shogo`
* Code styling
* FAQ
* References
* Writing Terraform configurations
* Workshop

Have you created a working branch from the [`ja`](https://github.com/antonbabenko/terraform-best-practices/tree/ja)  branch?

**Comment by antonbabenko** [comment]
@shogo452, please send me your email address (to anton@antonbabenko.com), so you can access the GitBook platform we use for the translations.

**Comment by t-okamoto1122** [comment]
@shogo452 
Before we begin let's adjust out Japanese doccument taste.
I have listed the areas where individual differences may appear when translating into Japanese.

日本語翻訳する場合、「人によって迷いが発生しそうだな、先に方針を揃えておいたほうがよさそうだな」と個人的に思う箇所を挙げておきます
(あくまで私の個人意見なので別の案があればお知らせくださいね！)

- ですます調　or だ/である調
  --> 今回は「ですます調」でいきましょう
　なんとなく柔らかい雰囲気を感じるのでw

- カタカナ英語
  --> 無理に日本語にすると違和感があるものはカタカナでいきましょう
      e.g. コンポーネント

- 句読点(そこまで迷いはでないかも..
  --> 基本英文の方でピリオドで終わっているものは「。」で
        逆に句読点つけると違和感でる箇所があれば無しで良いかと思っています！

**Comment by shogo452** [comment]
@t-okamoto1122 
Thank you for your suggestion.
提案ありがとうございます！上記に合わせます！

**Comment by shogo452** [comment]
@t-okamoto1122 
Next, I'll take on the following pages

* FAQ
* References

### Page List

* Welcome ( `Takashi`
* Key concepts ( `Takashi`
* Code structure ( `Shogo`
* Code structure examples  ( `Takashi`
* Naming conventions ( `Shogo`
* Code styling  ( `Takashi`
* FAQ ( `Shogo`
* References  ( `Shogo`
* Writing Terraform configurations
* Workshop

**Comment by t-okamoto1122** [comment]
@shogo452 
I'll do Writing Terraform configurations & Workshop

**Comment by shogo452** [comment]
@t-okamoto1122 
I have merged the pages I was in charge of.

**Comment by t-okamoto1122** [comment]
@shogo452 
Thank you.
I have also completed my pages.
Let's end with a brief review of each other's pages.

**Comment by t-okamoto1122** [comment]
@shogo452 
I would like to discuss the term “infrastructure module”.

I'd like to unify all “infrastructure” with “インフラ” to avoid making the text longer.
By the way, I checked O'REILLY's book “詳解 Terraform”, and all “infrastructure module” is translated as “インフラモジュール”.

Other areas seemed fine.

**Comment by shogo452** [comment]
@t-okamoto1122 
Thank you for your feedback.
I fix them to "インフラ" .

I would like to request modifications to the following sections.

* `ようこそ`
  * 厳密には物理本では無いため下記の方が良いかと思ったのですがどうでしょうか？
    *   `この本で説明されている情報の一部は、....` -> `本書で 説明されている情報の一部は、....`
    * `この本に収めることを目指しています。` -> `本書に収めることを目指しています。`
* `Terraform 設定ファイルの記述`
  *  冒頭の`記述`が消し忘れのようでしたら削除をお願いしたいです。

I think the other sections are fine.

**Comment by t-okamoto1122** [comment]
@shogo452 
thank you for your review and I've fixed them.

@antonbabenko 
We all done!

**Comment by antonbabenko** [comment]
Thank you guys for the work! I will mention it today in the [Terraform Weekly newsletter](https://www.weekly.tf) and on LinkedIn.

**Comment by shogo452** [comment]
@antonbabenko 
Thank you for sharing in the Terraform Weekly newsletter.
I would appreciate it if you could add the national flag to the About section of the repository.

> ### About
> Terraform Best Practices free ebook translated into 🇬🇧🇦🇪🇧🇦🇧🇷🇫🇷🇬🇪🇩🇪🇬🇷🇮🇱🇮🇳🇮🇩🇮🇹🇰🇷🇵🇱🇷🇴🇨🇳🇪🇸🇹🇷🇺🇦🇵🇰

**Comment by antonbabenko** [comment]
Great catch! I have just updated the flags with Japan being in the middle :)
